import { Category, Product } from '@/core/types/catalog';
import { Banner } from '@/core/types/banner';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-burgers',
    nombre: 'Artisan Burgers',
    orden: 1,
    imagenUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?fm=webp&w=480&q=65',
  },
  {
    id: 'cat-pizzas',
    nombre: 'Craft Pizzas',
    orden: 2,
    imagenUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?fm=webp&w=480&q=65',
  },
  {
    id: 'cat-sides',
    nombre: 'Sides & Fries',
    orden: 3,
    imagenUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?fm=webp&w=480&q=65',
  },
  {
    id: 'cat-drinks',
    nombre: 'Drinks & Craft Soda',
    orden: 4,
    imagenUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?fm=webp&w=480&q=65',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-truffle-burger',
    nombre: 'Truffle Bacon Smash Burger',
    descripcion: 'Double smashed prime beef patties, black truffle aioli, smoked cheddar, crispy bacon on brioche.',
    precio: 14.50,
    stock: 50,
    categoria: 'cat-burgers',
    orden: 1,
    imagenUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?fm=webp&w=480&q=65',
  },
  {
    id: 'prod-bbq-burger',
    nombre: 'Smoked Bourbon BBQ Burger',
    descripcion: 'Aged Angus beef, onion rings, cheddar, spicy bourbon BBQ glaze and pickles.',
    precio: 13.90,
    stock: 35,
    categoria: 'cat-burgers',
    orden: 2,
    imagenUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?fm=webp&w=480&q=65',
  },
  {
    id: 'prod-margherita-pizza',
    nombre: 'San Marzano Margherita',
    descripcion: 'Authentic 48h sourdough crust, San Marzano tomatoes, fresh buffalo mozzarella, basil & EVOO.',
    precio: 16.00,
    stock: 25,
    categoria: 'cat-pizzas',
    orden: 1,
    imagenUrl: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?fm=webp&w=480&q=65',
  },
  {
    id: 'prod-pepperoni-honey',
    nombre: 'Spicy Pepperoni & Hot Honey',
    descripcion: 'Artisanal pepperoni, spicy Calabrese salami, mozzarella, and chili-infused organic hot honey.',
    precio: 17.50,
    stock: 30,
    categoria: 'cat-pizzas',
    orden: 2,
    imagenUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?fm=webp&w=480&q=65',
  },
  {
    id: 'prod-truffle-fries',
    nombre: 'Parmesan Truffle Fries',
    descripcion: 'Hand-cut crispy rustic potatoes tossed in white truffle oil, grated parmesan, and fresh rosemary.',
    precio: 6.50,
    stock: 60,
    categoria: 'cat-sides',
    orden: 1,
    imagenUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?fm=webp&w=480&q=65',
  },
  {
    id: 'prod-onion-rings',
    nombre: 'Crispy Beer Battered Rings',
    descripcion: 'Jumbo sweet onions in IPA craft batter served with house smoked chipotle dipping sauce.',
    precio: 5.90,
    stock: 40,
    categoria: 'cat-sides',
    orden: 2,
    imagenUrl: 'https://images.unsplash.com/photo-1639024471285-0afc86ab16f0?fm=webp&w=480&q=65',
  },
  {
    id: 'prod-craft-lemonade',
    nombre: 'Berry Basil Craft Lemonade',
    descripcion: 'Cold-pressed lemons, wild raspberry reduction, sparkling soda, and muddled sweet basil.',
    precio: 4.50,
    stock: 100,
    categoria: 'cat-drinks',
    orden: 1,
    imagenUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?fm=webp&w=480&q=65',
  },
  {
    id: 'prod-craft-beer',
    nombre: 'Citra Hops Artisanal IPA',
    descripcion: 'Refreshing local craft beer with notes of passionfruit, grapefruit, and crisp pine finish (330ml).',
    precio: 5.50,
    stock: 50,
    categoria: 'cat-drinks',
    orden: 2,
    imagenUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?fm=webp&w=480&q=65',
  },
];

export const MOCK_BANNERS: Banner[] = [
  {
    id: 'banner-1',
    title: 'Weekend Gourmet Feast',
    description: 'Get free artisan truffle fries on all orders over $30 placed via WhatsApp.',
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?fm=webp&w=480&q=60',
    active: true,
    order: 1,
    createdAt: new Date(),
    link: '/category/cat-burgers',
  },
  {
    id: 'banner-2',
    title: 'Artisan Wood-Fired Pizzas',
    description: '48h slow fermented sourdough crust with genuine Italian ingredients.',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?fm=webp&w=480&q=60',
    active: true,
    order: 2,
    createdAt: new Date(),
    link: '/category/cat-pizzas',
  },
];
